### ISSUE TITLE
phpLDAPadmin shows "This base cannot be created with PLA"

### ISSUE THREAD

**Issue by ajnikitins** [ajnikitins/dockeria#1]
Logging in with a user (should test with other users) succeeds, but cannot access the LDAP tree. The message "This base cannot be created with PLA" is shown instead.

Possibly invalid phpLDAPadmin configuration.

**Comment by ajnikitins** [comment]
Fixed by manually editing phpLDAPadmin configuration.

**Comment by juluanb** [comment]
Hi @ajnikitins, could you give details about what kind of changes you made to make it work? We have the same problem here.
